update/0.4.6
venuenext/venuenextsdkdemo-ios pull request #8
Opened 2019-11-25 22:32 UTC by derek-bertubin

Signed-off-by: Derek Bertubin <derek.bertubin@venuenext.com>

2019-11-26 18:08 UTC, NFulkerson approved these changes

2019-12-02 15:40 UTC, NFulkerson requested changes

2019-12-02 15:40 UTC, NFulkerson commented on VenueNextSDK-Demo/AppDelegate.swift
> +        PresenceSDK.getPresenceSDK().setConfig(consumerKey: "NCA8hpkFiPJsDp03oX0sTXZri1jYLvhY", displayName: "Demo App", useNewAccountsManager: true)
This needs to get scrubbed.

2019-12-02 15:40 UTC, NFulkerson commented on VenueNextSDK-Demo/AppDelegate.swift
> +            VenueNext.shared.initialize(sdkKey: "vn:venuenext:dev:ios-sdk-WVtWMWcBZSItKf7lbEtxP9GsEgW0XqCmI1Y=", sdkSecret: "vn:venuenext:dev:ios-sdk-WVtWMWcBZSItKf7lbEtxP9GsEgW0XqCmI1Y=")
So does this.

2019-12-02 17:49 UTC, NFulkerson approved these changes

2019-12-02 17:56 UTC, rramdeen approved these changes

2019-12-04 14:22 UTC, merged